### PR TITLE
Remove support for ruby 1.9 and ruby 2.0

### PR DESCRIPTION
**Pull request by tjouan**
This change is based on original work from @deivid-rodriguez, thanks!
See original version at:

  https://github.com/Locale/localeapp/pull/203

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
@tjouan Does the gem still work with 1.9.3 after these changes? If this a breaking change (and not just a "support is no longer guaranteed" kind of change), maybe you also want to restrict the minimum ruby version in your `gemspec` file.

**Comment by tjouan** [comment]
@deivid-rodriguez,

I honestly don't know, but upcoming changes on the gem (other PRs)
might not help for ruby 1.9.

For now this is more the "support is no longer guaranteed" version,
I'm not sure if we already want to make it "more difficult" to use for
unsupported ruby versions.

One benefit I see is it might help user support, nobody would attempt
to use it on ruby 1.9 for example. However, one problem I see is that
as maintainers, we may want only one "level" of support, so in that
scenario we would most probably force ruby >= 2.0 usage, same as our
CI builds.

**Comment by deivid-rodriguez** [comment]
Well, adding a `required_ruby_version` constraint in the `gemspec` will not make it "more difficult", it will make it fail at installation time with a (helpful) "Ruby 1.9 is not supported" message. If the gem no longer works on ruby 1.9, this is definitely the best thing to do.

I feel this is the safest thing to do anyways since once you stop testing in CI against 1.9.3, you'll never know when you actually break support. So I'd say just restrict the minimum required ruby version and bump the major version number of the gem in the next release.

**Comment by thibaultdalban** [comment]
Yep I agree !

**Comment by tjouan** [comment]
PR updated with this change:
``` diff
--- a/localeapp.gemspec
+++ b/localeapp.gemspec
@@ -20,6 +20,8 @@ Gem::Specification.new do |s|
   s.executables   = `git ls-files -- bin/*`.split("\n").map{ |f| File.basename(f) }
   s.require_paths = ["lib"]
 
+  s.required_ruby_version = ">= 2.1"
+
   s.add_dependency('mime-types', '~> 2.6')
   s.add_dependency('i18n', '~> 0.4')
   s.add_dependency('json', '~> 1.8')
```

Just to clarify, when I meant "more difficult", I was thinking of for example an user who would use the standard gem version, and implement his own monkey patch to support an unsupported ruby release (if needed), he can still easily use normal gem release from rubygems, without having to patch gem specification that we cannot do at runtime.

**Comment by deivid-rodriguez** [comment]
Aaah I see. In that case, totally up for making that more difficult! :)

**Pull request merged**
