### PR TITLE
Support multi-line translations via command line

### PR DESCRIPTION
**Pull request by aaronjensen**

### CODE REVIEW

**Comment by michaelbaudino** [comment]
Hi @aaronjensen, thanks a lot for the contribution.
Your use case is to allow a command like this, right ?
```
$ localeapp add key.name en:"test\
content" es:"spanish\
content"
```

**Comment by aaronjensen** [comment]
Yes, something like that. Though my *real* use case in this case is writing a `$ locale cp` script. `locale mv` doesn't work in our project for renames because we can't take a string out of existence until the new one is in use in production.

**Comment by michaelbaudino** [comment]
Alright, I just wanted to double-check what we were trying to achieve with with this PR :smiley:

**Comment by michaelbaudino** [comment]
It's in freshly-released 0.9.3 version!
Thanks again for the contribution @aaronjensen :+1:

**Comment by aaronjensen** [comment]
Thanks! You may also want to update the changelog.

**Comment by michaelbaudino** [comment]
Argh... Fixed!
Thanks.

**Pull request merged**
