### PR TITLE
Drop 1.9.3 support

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
Superseding #202.

That started as a simple update of the `rest-client` gem and ended up being more than that. Opening a new PR under a branch with a more meaningful name.

I'll be doing further work (if necessary) here and testing my apps against this branch.

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
Ok, this is ready. I've tried it against my app and it's working fine.

Some comments:

* I've made some changes to just relax version dependencies for `json` and `rest-client` instead of just dropping support for old versions.

* In the case of `mime-types`, I've just dropped the dependency since I don't think is a dependency of this gem.

* I see you've removed the _hakiri_ check, so maybe you want 8ef4bc1 removed and keep support for the insecure versions?

* If you want to keep 1.9.3 compatibility, I can also remove 240d4f7 and this PR would be backwards compatible (I think).

Regards!

**Comment by deivid-rodriguez** [comment]
Issues with bundler seem fixed in the latest bundler release, `1.13.0`, so I removed some workarounds I had to add to `.travis.yml` to get this passing.

**Comment by michaelbaudino** [comment]
Hi @deivid-rodriguez and thanks a lot for this PR.

Unfortunately, and despite the fact that I love to use decently recent versions of gems too, we can absolutely not merge such changes since they defeat a gem purpose: reusability.

Those changes remove support for Ruby 1.9.3 (which, to be honest, we considered recently too since it's now EOL'd since a while) but also a lot of versions of i18n. What we want to achieve with this gem is to make it usable by as many people/projects as possible, so forbid its use to any person/project using Ruby 1.9.3 or any version of I18n prior to 0.7 definitely sounds like the path we do not want to take.

That's exactly why gems almost never include a `Gemfile.lock` like this PR does: it locks every user to the exact version we're defining in it, which is not (and must absolutely not be, imho) the responsability of the gem! (it should be the responsability of the project using this gem)

I hope this is clear and explains why I'm closing this PR, but I'd like to thank and congratulate you again for the work and effort you put in this, I really appreciate it.

**Comment by deivid-rodriguez** [comment]
> Hi @deivid-rodriguez and thanks a lot for this PR.

Thanks for replying, @michaelbaudino.

> Unfortunately, and despite the fact that I love to use decently recent versions of gems too, we can absolutely not merge such changes since they defeat a gem purpose: reusability.

> Those changes remove support for Ruby 1.9.3 (which, to be honest, we considered recently too since it's now EOL'd since a while) but also a lot of versions of i18n. What we want to achieve with this gem is to make it usable by as many people/projects as possible, so forbid its use to any person/project using Ruby 1.9.3 or any version of I18n prior to 0.7 definitely sounds like the path we do not want to take.

I wonder if you have you read my other messages. I address exactly those two concerns and propose to remove the specific commits from the PR if you're not happy with either of the changes. Regarding support for different `i18n` versions, the only reason I removed it is because your _own_ Hakiri check does not pass otherwise. Thanks for introducing me to that service, by the way! :) Regarding 1.9.3, well, it's totally up to you to keep supporting such an old version.

> That's exactly why gems almost never include a Gemfile.lock like this PR does: it locks every user to the exact version we're defining in it, which is not (and must absolutely not be, imho) the responsability of the gem! (it should be the responsability of the project using this gem)

This is wrong. `Gemfile.lock` is ignored at both runtime or installation time of a gem, it's only used during development. So it doesn't lock users of the gem to anything, just developers of it. Please keep using the `.gemspec` file for this in the future, or you'll get disappointed... :). I like committing `Gemfile.lock` to version control to ensure all the _developers_ of the gem get an easily reproducible environment.  There are definitely better ways to ensure you gem works and can be installed against different versions of dependencies. This is definitely not `Gemfile.lock`'s responsability. For example, you can use `Appraisals` which you are using for ensuring `i18n` compatibility. In any case, I can absolutely remove ccf9ab3 too.

> I hope this is clear and explains why I'm closing this PR, but I'd like to thank and congratulate you again for the work and effort you put in this, I really appreciate it.
 
No, unfortunately it doesn't explain why you discard all changes just because you're not interested in two or three of them. In particular, I'm interesed in being able to use the gem with higher versions of the `rest-client` and `json` gems (fc7dd2b and 7f07af2).

Let me know.

**Comment by deivid-rodriguez** [comment]
I just revisited this and saw the travis CI logs where @tjouan seems to try to fullfil my request for allowing more recent versions of dependencies.

@tjouan Can I help you? I had a look at the logs and you're running into the same errors I got. Feel free to reuse my work instead of redoing it :wink:. By the way, those logs are a good example of why I think commiting lock files to version control is a good thing.

@michaelbaudino The commits in this branch are split into logical units, so it would be very easy to remove whatever it is that you don't like. Just let me know!

**Comment by michaelbaudino** [comment]
@deivid-rodriguez Yes, thanks a lot, we'll be looking how we can achieve your goal (use `localeapp` with recent versions of `rest-client` and `json`) in the next few days/weeks.

**Comment by deivid-rodriguez** [comment]
@michaelbaudino Thanks for reopening. I'm not sure I got your message though. Are you saying that you would like me to remove those commits from the PR or that I shouldn't bother because you will work on this yourselves?

**Comment by tjouan** [comment]
@deivid-rodriguez hello, we haven't decided anything yet. @michaelbaudino and me need to discuss this, mainly because in current form it's not in line with an important decision we took last month regarding 1.9 support, and how we maintain this gem.

I did reuse your work a few weeks ago, it was just to check why we changed the few dependency requirements you also changed in this PR (to be sure it was only for 1.9 support). I couldn't use all simply because they wouldn't all apply cleanly "alone" (bundler lock file etc…) of course.

In all case your work is useful to us, thanks again. No need to change until we take the time to think about this and discuss all possible solutions, then we'll let you know if and how we intend to solve this.

**Comment by deivid-rodriguez** [comment]
Oh, I had forgotten that I removed 1.9 support to actually be able to upgrade those dependencies... My bad.

So I think your options are:

* Keep 1.9.3 support and disallow json 2 and rest-client 2. Doesn't sound very appealing and will sound worse as time passes.
* Work out some magic adding a C-extension, so you can run some custom Ruby code at installation time and declare dynamic dependencies according to user's ruby version. Doesn't sound very appealing either, but will stay as appealing as it is now as time passes.
* Drop 1.9.3, which doesn't sound appealing to you right now but will probably sound better as time passes.

Just don't worry about my use case for making your decision, I've been happily using this branch in production for a while.

Regarding reusing each others work, I recommend you have a look at `git cherry-pick`, it's cool! :wink:

**Comment by deivid-rodriguez** [comment]
Well, there's also a fourth option. The "extended set of dependencies" (`json '>= 1.9, '< 3'` and `rest-client '>= 1.8', '< 3'`) seems "resolvable" to me in both 1.9 and 2.x rubies (just pick 1.x versions for Ruby 1.9, and 2.x versions for ruby 2.x).

So maybe you could report this to `bundler` and they might acknowledge this as a bug and fix it. 

I'm talking about this error here, by the way

```
$ bundle
Fetching gem metadata from https://rubygems.org/........
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
json-2.0.2 requires ruby version ~> 2.0, which is incompatible with the current version, ruby 1.9.3p551
```

**Comment by tjouan** [comment]
Thank you for all this additional information. We haven't worked on it
yet, but will be useful when we will :-)

**Comment by deivid-rodriguez** [comment]
Closing since you're doing this yourselves. Glad you chose to move forward :)

**Comment by tjouan** [comment]
hello @deivid-rodriguez,

yes, sorry I did not updated this PR yet, was waiting a little that
PRs related to the build or other detail were merged, so I could point
you to the branch with ruby 1.9 support removal.

We should merge something similar to current
`feature/remove-support-rubies_old` branch, but it might change a
little depending on next reviews and/or merge.

But I guess I won't learn you anything as you follow updates and PR on
the repository :-)

Thanks again for your work, especially the parts on YAML handling with
`Syck` and `Psych` which I missed in my own work at first!

**Comment by deivid-rodriguez** [comment]
No problem, thanks for the update!

I don't really watch the repository, but I recently upgraded a couple of apps to Rails 5 and that reminded my that I'm actually pointing to this branch here: https://github.com/alabs/nolotiro.org/blob/master/Gemfile#L63-L65. So I came to check if you had moved forward and I can get rid of that :)

**Comment by tjouan** [comment]
hello @deivid-rodriguez,

FYI `master` branch is now less strict about required runtime
dependencies.
ruby 2.4 should work if you need it too.
We will make a new gem release in the next days.

**Comment by deivid-rodriguez** [comment]
Thanks @tjouan, will switch to master as soon as I can! :wink:

**Pull request closed without merging**
